### PR TITLE
Allow Executing Callbacks on Non-URL Strings

### LINKED ISSUE #23: Allow Executing Callbacks on Non-URL Parts
Hi, 

I'm using this as part of a series of parsing treatments to strings that I need to chain together, e.g.
```
string = 'Hello I am https://google.com a special string'
... // string treatments
string is now: <span>Hello I am <a href='https://google.com'>https://google.com</a> a <span class='special'>special</span> string</span>
```
I was wondering if, to facilitate this, `AnchorifyText` could take in an optional prop which would be a function executed on all non-match strings. This way I could chain the two parsers together to achieve a result like the one above. Would that be possible?

### PR DESCRIPTION
**Pull request by ragurney**
Resolves #23

### CODE REVIEW

**Comment by ragurney** [comment]
@georgeOsdDev ready for a review!

**Comment by ragurney** [comment]
Bumping this again @georgeOsdDev. Any chance you could take a look?

**Comment by ragurney** [comment]
@georgeOsdDev 💇‍♂

**Comment by georgeOsdDev** [comment]
@ragurney 
Thanks! I'll publish new version soon 👍

**Pull request merged**
